# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

"""
Report Generator
================
Produces structured medical diagnostic reports. When an LLM endpoint is
configured the report narrative is generated by the LLM; otherwise a
high-quality, evidence-based template is used.
"""

import httpx
from datetime import datetime, timezone
from typing import Optional

from app.config import settings
from app.models import (
    ImageAnalysisResult,
    SymptomAnalysisResult,
    PatientResponse,
    Severity,
)


# ─────────────────────────── Severity helper ─────────────────────────────────

_SEVERITY_COLOR = {
    Severity.NONE: "🟢 None",
    Severity.MILD: "🟡 Mild",
    Severity.MODERATE: "🟠 Moderate",
    Severity.SEVERE: "🔴 Severe",
    Severity.CRITICAL: "🚨 Critical",
}

_URGENCY_MAP = {
    "routine": "Routine follow-up is adequate.",
    "urgent": "Follow-up within 24–48 hours or at the next available appointment.",
    "emergency": "IMMEDIATE evaluation and intervention required.",
}


# ─────────────────────────── Template builder ────────────────────────────────

class ReportGenerator:
    """Generates a structured SOAP-style diagnostic report."""

    async def generate(
        self,
        patient: PatientResponse,
        image_result: Optional[ImageAnalysisResult],
        symptom_result: Optional[SymptomAnalysisResult],
        primary_diagnosis: str,
        severity: Severity,
        confidence: float,
        requesting_physician: Optional[str] = None,
    ) -> dict:
        """Return a dict with keys: clinical_summary, findings, assessment, plan, follow_up."""

        if settings.LLM_ENDPOINT_URL:
            try:
                return await self._llm_generate(
                    patient, image_result, symptom_result,
                    primary_diagnosis, severity, confidence, requesting_physician
                )
            except Exception:
                pass  # Fallback to template

        return self._template_generate(
            patient, image_result, symptom_result,
            primary_diagnosis, severity, confidence, requesting_physician
        )

    # ──────────────── Template-based ────────────────

    def _template_generate(
        self,
        patient: PatientResponse,
        image_result: Optional[ImageAnalysisResult],
        symptom_result: Optional[SymptomAnalysisResult],
        primary_diagnosis: str,
        severity: Severity,
        confidence: float,
        requesting_physician: Optional[str],
    ) -> dict:
        now = datetime.now(timezone.utc).strftime("%B %d, %Y — %H:%M UTC")
        age = self._calculate_age(patient.date_of_birth)

        # ── SUBJECTIVE ────────────────────────────────────────────────────────
        sx_lines = []
        if symptom_result:
            sx_list = ", ".join(symptom_result.matched_diseases[0].matching_symptoms[:6]) \
                if symptom_result.matched_diseases else "none documented"
            sx_lines.append(f"Chief complaint: {sx_list}.")
            if symptom_result.red_flags:
                sx_lines.append(
                    f"Red-flag symptoms identified: {', '.join(symptom_result.red_flags)}."
                )
        if not sx_lines:
            sx_lines.append("Patient presented for routine medical evaluation.")

        clinical_summary = (
            f"Report generated: {now}\n"
            f"Patient: {patient.first_name} {patient.last_name} | "
            f"Age: {age} | Gender: {patient.gender.capitalize()} | "
            f"Blood type: {patient.blood_type or 'Unknown'}\n"
            f"Chronic conditions: {patient.chronic_conditions or 'None documented'}\n"
            f"Current medications: {patient.current_medications or 'None documented'}\n"
            f"Requesting physician: {requesting_physician or 'Self-referred'}\n\n"
            + " ".join(sx_lines)
        )

        # ── OBJECTIVE / FINDINGS ──────────────────────────────────────────────
        finding_lines = []
        if image_result:
            finding_lines.append(
                f"Imaging ({image_result.modality.value.replace('_', ' ').title()}):\n"
                f"  Status: {image_result.status.value.upper()}\n"
                f"  Primary finding: {image_result.primary_diagnosis}\n"
                f"  Confidence: {image_result.confidence_score * 100:.1f}%\n"
                f"  Severity: {_SEVERITY_COLOR.get(image_result.severity, image_result.severity.value)}\n"
                f"  Recommendation: {image_result.recommendation}"
            )
            for f in image_result.findings:
                finding_lines.append(
                    f"  → [{f.label}] in {f.region or 'unspecified region'}: "
                    f"{f.description} (confidence {f.confidence * 100:.1f}%)"
                )

        if symptom_result:
            top3 = symptom_result.matched_diseases[:3]
            lines = [
                f"  • {m.disease} — probability {m.probability * 100:.1f}% "
                f"[ICD-10: {m.icd10_code or 'N/A'}]"
                for m in top3
            ]
            finding_lines.append(
                "Symptom Analysis:\n"
                + "\n".join(lines)
                + f"\n  Urgency: {symptom_result.urgency.upper()}"
            )
            if symptom_result.recommended_tests:
                finding_lines.append(
                    "Recommended diagnostic tests:\n  "
                    + "\n  ".join(f"• {t}" for t in symptom_result.recommended_tests[:6])
                )

        findings = "\n\n".join(finding_lines) if finding_lines else "No objective findings documented."

        # ── ASSESSMENT ────────────────────────────────────────────────────────
        diff_list = (image_result.differential_diagnoses if image_result else [])[:4]
        assessment = (
            f"Primary diagnosis: {primary_diagnosis}\n"
            f"Confidence: {confidence * 100:.1f}%\n"
            f"Severity: {_SEVERITY_COLOR.get(severity, severity.value)}\n"
        )
        if diff_list:
            assessment += "\nDifferential diagnoses:\n" + "\n".join(f"  • {d}" for d in diff_list)

        # ── PLAN ──────────────────────────────────────────────────────────────
        plan_lines = []
        if image_result and image_result.recommendation:
            plan_lines.append(f"Imaging follow-up: {image_result.recommendation}")
        if symptom_result and symptom_result.specialist_referral:
            plan_lines.append(f"Specialist referral: {symptom_result.specialist_referral}")
        if symptom_result and symptom_result.recommended_tests:
            tests = "; ".join(symptom_result.recommended_tests[:4])
            plan_lines.append(f"Immediate investigations: {tests}.")
        if patient.allergies:
            plan_lines.append(
                f"Note allergy profile before prescribing: {patient.allergies}."
            )
        plan = "\n".join(f"• {l}" for l in plan_lines) if plan_lines else "• Individualised management plan to be determined by the treating physician."

        # ── FOLLOW-UP ─────────────────────────────────────────────────────────
        urgency_str = "routine"
        if symptom_result:
            urgency_str = symptom_result.urgency
        follow_up = (
            f"{_URGENCY_MAP.get(urgency_str, 'Follow-up as clinically indicated.')}\n"
            f"Re-evaluate with treating physician and review all pending investigations."
        )

        return {
            "clinical_summary": clinical_summary,
            "findings": findings,
            "assessment": assessment,
            "plan": plan,
            "follow_up": follow_up,
        }

    # ──────────────── LLM-based ──────────────────────────────────────────────

    async def _llm_generate(
        self,
        patient: PatientResponse,
        image_result: Optional[ImageAnalysisResult],
        symptom_result: Optional[SymptomAnalysisResult],
        primary_diagnosis: str,
        severity: Severity,
        confidence: float,
        requesting_physician: Optional[str],
    ) -> dict:
        age = self._calculate_age(patient.date_of_birth)
        ctx_parts = [
            f"Patient: {patient.first_name} {patient.last_name}, {age} y/o {patient.gender}.",
            f"Chronic conditions: {patient.chronic_conditions or 'none'}.",
            f"Medications: {patient.current_medications or 'none'}.",
        ]
        if image_result:
            ctx_parts.append(
                f"Imaging ({image_result.modality.value}): {image_result.primary_diagnosis} "
                f"(confidence {image_result.confidence_score:.0%}, "
                f"severity {image_result.severity.value})."
            )
        if symptom_result and symptom_result.matched_diseases:
            top = symptom_result.matched_diseases[0]
            ctx_parts.append(
                f"Top symptom match: {top.disease} ({top.probability:.0%})."
            )
            if symptom_result.red_flags:
                ctx_parts.append(f"Red flags: {', '.join(symptom_result.red_flags)}.")

        ctx_parts.append(
            f"Primary diagnosis: {primary_diagnosis} | Severity: {severity.value} | "
            f"Confidence: {confidence:.0%}."
        )

        prompt = (
            "You are a senior physician generating a structured SOAP medical report. "
            "Using the clinical context below, produce concise but comprehensive sections:\n"
            "1. CLINICAL SUMMARY (patient info + chief complaint)\n"
            "2. FINDINGS (objective data from imaging and symptom analysis)\n"
            "3. ASSESSMENT (diagnosis + differentials)\n"
            "4. PLAN (immediate management steps)\n"
            "5. FOLLOW-UP (urgency and next steps)\n\n"
            "Clinical context:\n" + "\n".join(ctx_parts) + "\n\n"
            "Return each section clearly labelled."
        )

        async with httpx.AsyncClient(timeout=60) as client:
            resp = await client.post(
                f"{settings.LLM_ENDPOINT_URL}/v1/chat/completions",
                json={
                    "model": settings.LLM_MODEL,
                    "messages": [{"role": "user", "content": prompt}],
                    "max_tokens": settings.LLM_MAX_TOKENS,
                    "temperature": 0.3,
                },
            )
            resp.raise_for_status()
            text = resp.json()["choices"][0]["message"]["content"]

        # Parse sections from LLM output
        sections = {
            "clinical_summary": self._extract_section(text, "CLINICAL SUMMARY"),
            "findings": self._extract_section(text, "FINDINGS"),
            "assessment": self._extract_section(text, "ASSESSMENT"),
            "plan": self._extract_section(text, "PLAN"),
            "follow_up": self._extract_section(text, "FOLLOW-UP"),
        }
        # Fallback to template for any missing section
        tmpl = self._template_generate(
            patient, image_result, symptom_result,
            primary_diagnosis, severity, confidence, requesting_physician,
        )
        for k, v in sections.items():
            if not v:
                sections[k] = tmpl[k]
        return sections

    @staticmethod
    def _extract_section(text: str, header: str) -> str:
        """Extract content after a section header up to the next numbered section."""
        import re
        pattern = rf"(?:^|\n)\s*\d?\.*\s*{re.escape(header)}[:\s]*\n(.*?)(?=\n\s*\d\.|$)"
        match = re.search(pattern, text, re.IGNORECASE | re.DOTALL)
        return match.group(1).strip() if match else ""

    @staticmethod
    def _calculate_age(dob: str) -> str:
        try:
            birth = datetime.strptime(dob, "%Y-%m-%d")
            today = datetime.now(timezone.utc)
            age = today.year - birth.year - ((today.month, today.day) < (birth.month, birth.day))
            return f"{age}"
        except Exception:
            return "N/A"


report_generator = ReportGenerator()
